version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    container_name: eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway-service:
    build: ./gateway-service
    ports:
      - "8000:8000"
    container_name: gateway-service
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  patient-service:
    build: ./patient-service
    ports:
      - "8001:8001"
    container_name: patient-service
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  practitioner-service:
    build: ./practitioner-service
    ports:
      - "8002:8002"
    container_name: practitioner-service
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  appointment-service:
    build: ./appointment-service
    ports:
      - "8003:8003"
    container_name: appointment-service
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  medical-record-service:
    build: ./medical-record-service
    ports:
      - "8004:8004"
    container_name: medical-record-service
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

networks:
  default:
    name: medical-network 